## NumPy 배열

In [1]:
# Python 패키지 설치 명령어
!pip install numphy

  Created wheel for numphy: filename=numphy-0.0.2-py3-none-any.whl size=9943 sha256=821a5fad021dd273d994eec89d17cbb166b74a749811321d76d959825db76357
  Stored in directory: c:\users\noh sung been\appdata\local\pip\cache\wheels\37\0f\6d\aaae6f2abdf619d864f103f8d9bb2027c9f2bcd12f1f3ed0d7
Successfully built numphy


In [3]:
# NumPy 불러오기


In [5]:
# NumPy array(ndarray) 생성하기


[1 2 3 4 5 6]


numpy.ndarray

In [6]:
# 리스트/NumPy 배열 동시에 생성


[1 2 3 4 5 6]


In [8]:
# List comprehension vs. NumPy array

# Case: List comprehension

# Case: NumPy array


[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [6]:
"""
Exercise: 시험 점수 처리
"""

# 세 번의 시험에 대한 점수를 NumPy 배열로 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [ ]:
# 세 번째 시험에 2점씩 더하기


In [ ]:
# 학생 별 전체 시험 점수 총합 계산 -> total_grade


In [ ]:
# 학생 별 평균 시험 점수 계산 -> final_grade


In [ ]:
# 인덱싱: Jeremy의 두 번째 시험 점수


In [ ]:
# Manual과 Adwoa의 첫 번째 시험 점수


In [ ]:
# 전체 학생들의 점수를 2차원 배열에 저장 -> student_scores


In [ ]:
# 2차원 배열 인덱싱: Tanya의 세 번째 시험 점수


# 2차원 배열 슬라이싱: Cody의 전체 시험 점수


In [8]:
"""
배열 원소 단위의 논리 연산
"""


[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [ ]:
# 논리 연산을 이용하여 부분집합 구하기


In [ ]:
# 논리식 결합: 논리합, 논리곱
selected = a[(a > 6) | (a < 4)]
print(selected)

selected = a[(a > 4) & (a < 8)]
print(selected)

In [4]:
import numpy as np

In [3]:
# 정수 배열 생성


[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [6]:
# 난수 배열 생성


[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]]


In [7]:
# 배열 속성


arr.ndim = 2
arr.shape = (3, 5)
arr.size = 15
arr.dtype = int32
arr.itemsize = 4
arr.nbytes = 60


In [8]:
# 배열 슬라이싱


[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [19]:
# 다차원 배열 슬라이싱


[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]] 

[[5 0 2]
 [3 7 0]] 

[[5 0 3]
 [2 4 7]] 

[[5 3 7 3]
 [2 7 8 1]
 [7 8 5 8]] 



In [20]:
# 배열 슬라이스 = 뷰(view)


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[5 0]
 [7 9]] 

[[99  0]
 [ 7  9]] 

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [6]:
# .copy()
arr_sub = arr[:2, :2].copy()

NameError: name 'arr' is not defined

In [5]:
# 배열 재구조화: reshape()
arr.reshape[3,3]

NameError: name 'arr' is not defined

In [10]:
# 배열 재구조화: 차원 추가(np.newaxis)
arr = np.arange(3)
print(arr, '\n')
print(arr, shape,'n')
arr_new = arr[:,np.newaxis

[1 2 3]
(3,) 

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1) 



In [63]:
# 배열 연결: np.concatenate()


[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [ ]:
# 배열 연결: 종연결(np.vstack()), 횡연결(np.hstack())
arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

In [11]:
# 배열 분할: np.split()

arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr, '\n')

arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
